[package]
name = "rmp3"
version = "0.1.0"
authors = ["viri <git@stuff.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
